### ISSUE TITLE
creating a model in bindsnet

### ISSUE THREAD

**Issue by ati6868** [BindsNET/bindsnet#347]
Hi 
i wanted to ask what is difference between creating a model with this code :

`class NN(nn.Module):`
`def __init__(self, input_size, num_classes):`

        super(NN, self).__init__()

        self.linear_1 = nn.Linear(input_size, num_classes)

        self.linear_1 = nn.Linear(input_size, h)

        self.linear_2 = nn.Linear(h, num_classes)`

    def forward(self, x):
        out = torch.sigmoid(self.linear_1(x.float().view(-1)))
        out = torch.sigmoid(self.linear_2(out))
        return out`
and creating a network  with this model:
both do the same?

`network = Network(dt=dt)`
`inpt = Input(784, shape=(1, 28, 28))`
`network.add_layer(inpt, name="I")`
`output = LIFNodes(n_neurons, thresh=-52 + np.random.randn(n_neurons).astype(float))`
`network.add_layer(output, name="O")`
`C1 = Connection(source=inpt, target=output, w=0.5 * torch.randn(inpt.n, output.n))`
`C2 = Connection(source=output, target=output, w=0.5 * torch.randn(output.n, output.n))`
`network.add_connection(C1, source="I", target="O")`
`network.add_connection(C2, source="O", target="O")`

could someone please explain what are differences exactly
thanks in advance

**Comment by dee0512** [comment]
Former is an artificial neural network(ANN), the latter is a spiking neural network(SNN). 

Former has 2 layers, latter has one layer with a recurrent connection.

(Also self.linear_1 has been overwritten for some reason.)

I am not sure why you are asking this. But hope this helped.  They do not behave similarly since they have different architecture and one is an ANN and the other is an SNN.

**Comment by ati6868** [comment]
Thanks @dee0512  for your response... i asked this because i saw it in reservoir.py example on bindsnet .... and i wanted to  know is there any difference generally
I have a problem with using Gradient Descent on SNN
and it was only example on bindsnet that has used GD ...

**Comment by ati6868** [comment]
Could please give me a help on this code about Gradient Descent:
`
learning_rate = 1e-6
for t in range(500):
    network.run(inpts=inpts, time=time)
    spikes = {"A": Input_monitor.get("s"), "B": LIF_monitor.get("s") }
    Generated_spikes=spikes["B"]
    sum_Generated_spikes =(Generated_spikes==1).sum(dim=0)
    loss = sum_Generated_spikes - images[0]
    if t % 100 == 99:
        print(t, loss.item())

    # Use autograd to compute the backward pass.
    loss.backward()

    # Update weights using gradient descent
    with torch.no_grad():
        w -= learning_rate * w.grad

        # Manually zero the gradients after updating weights
        w.grad.zero_()`

**Comment by ati6868** [comment]
i don't know exactly where i have to define my parameters `requires_grad=True` ...and when i run it 
it gives me this error:
`RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn`

**Comment by dee0512** [comment]
I don't think reservoir.py is gradient descent on SNN. Try these examples: 

[backprop](https://github.com/BINDS-LAB-UMASS/bindsnet_experiments/blob/master/experiments/mnist/backprop.py
)
[surrogate gradient](https://github.com/BINDS-LAB-UMASS/bindsnet_experiments/blob/master/experiments/mnist/surrogate_gradient.py)

Bindsnet experiments repo is where we put most of our experiments. However, it is not maintained. Therefore, the old code might break due to updates in BindsNET.

**Comment by ati6868** [comment]
Oh thanks a lot @dee0512  .... i will check them and i guess the links u sent me ,would help me very much
