### ISSUE TITLE
Problem about Poisson encoder

### ISSUE THREAD

**Issue by jcmharry** [BindsNET/bindsnet#381]
Why do the encoded spikes from the same picture change every time I run the eth_mnist? I find the spikes always change... Is there any error?

**Comment by jcmharry** [comment]
I find where the error is! When we set GPU=True, the encoded spikes from one picture change every time running the code.

**Comment by jcmharry** [comment]
Also one problem, why dies spikes from Poissonencoder change slightly every time? It's really confused.

**Comment by Danielle-Schuman** [comment]
Poisson encoding encodes the input data as spikes based on a probability distribution. Thus, certain input spikes only occur  with a certain probability, and thus they are different every time. And this also influences the other spikes in the network, since they are "calculated" from the input, leading to non-deterministic (i.e. being different every time you run it) spiking behaviour of the network. (At least that's one of the causes of the non-deterministic spiking behaviour, I don't know if there are more...)

**Comment by jcmharry** [comment]
> Poisson encoding encodes the input data as spikes based on a probability distribution. Thus, certain input spikes only occur with a certain probability, and thus they are different every time. And this also influences the other spikes in the network, since they are "calculated" from the input, leading to non-deterministic (i.e. being different every time you run it) spiking behaviour of the network. (At least that's one of the causes of the non-deterministic spiking behaviour, I don't know if there are more...)

Thanks for your reply. Yes, when I add the seed in the poisson encoding function, it generates the same spikes every time. But I still have another problem. When I run multiple iterations, although I input the same picture, the second layer's output spikes are not same. And when I use the GPU, the output spikes also are different from I use CPU.

**Comment by Hananel-Hazan** [comment]
Thanks @Danielle-Schuman.
@jcmharry note that it is recommended to set the seed for numpy as well. Also try to set the seed at the start of the iteration.
Because BindsNET use other packages, it is harder to determine where the randomness coming from.
