### ISSUE TITLE
Illegal memory access error on GPU

### ISSUE THREAD

**Issue by k18shruti** [BindsNET/bindsnet#389]
I am trying to simulate a randomly connected network of 50,000 neurons on the GPU (V100) and I am getting this error:
.../bindsnet/network/nodes.py", line 523, in forward
    self.refrac_count.masked_fill_(self.s, self.refrac)
RuntimeError: CUDA error: an illegal memory access was encountered

I did a pip install using: pip install git+https://github.com/BindsNET/bindsnet.git
Is there a way to fix this issue?

Thanks.

**Comment by Hananel-Hazan** [comment]
Thank you for using BindsNET. 

Sadly, it seems that the error that you encounter belongs to PyTorch. Searching the error message leads to PyTorch forums that try to troubleshoot the problem. Please look [here ](https://github.com/pytorch/pytorch/issues/21819) for more details. 

From what I see in the discussion this error seems quite generic message, that can be caused by many different reasons. 
It may be caused by the size of the data that is bigger than the GPU memory capacity. Or from a modification that was done to the GPU power limits. Or from many other reasons. 

Try to upgrade the PyTorch to the latest version and see if the problem continues. You can also try to tweak the BindsNET code to use 16bit size Tensors. That can increase the capacity of the neurons that can be used. But it also may lead to undesirable behavior of the neurons.
