### ISSUE TITLE
Optimization/Performance issue compared to Norse

### ISSUE THREAD

**Issue by Looper2074** [BindsNET/bindsnet#425]
https://github.com/norse/norse/tree/master/norse/benchmark

Performance compared to norse

**Comment by Hananel-Hazan** [comment]
Thank you for bringing this up, seems strange, but I will check it up.

**Comment by Hananel-Hazan** [comment]
I am not sure what version of BindsNET they used in their test. 
Running the Norse benchmark scripts produce the following results (excluding GeNN):
![1](https://user-images.githubusercontent.com/3954715/98124731-938c6c00-1e81-11eb-82e0-262d65f45dbb.png)

The hardware is Intel(R) Xeon(R) CPU E5-2687W v3 @ 3.10GHz with 64Gb RAM, GeForce GTX TITAN X with 12Gb.

Has statement in the Norse benchmark readme page, they stop measuring running time at 4000 neurons, because BindsNET script run out of memory. They are right, but it seems to cause by using wrong method of input. In their script they prepare a huge input matrix in the size of the network running time and use it as an input. If, however in file `bindsnet_lif.py` you replace line 24 to 33 with those lines:
```
from bindsnet.encoding import poisson
input_data = {"Input": poisson(
    datum=torch.rand(
            (parameters.batch_size, parameters.features),
                device=parameters.device),
        time=T * parameters.sequence_length, device=parameters.device)}
```
The script will run for more neurons. (how many? Depends on how much memory your GPU have.)

When benchmarking, it is also a good practice to nullify the network object after each run and to clean up before each test run, add the lines below after line 57 at `main.py` will insure that GPU memory and cache will be clean.
```
import gc 
gc.collect()
import torch
with torch.no_grad():
    torch.cuda.empty_cache() 
```
Here the result of the script after the corrections:
![final](https://user-images.githubusercontent.com/3954715/98124841-b3239480-1e81-11eb-884d-5a47855bc51f.png)

BindsNET run out of GPU memory on more than 130,000 neurons
Norse run out of GPU memory on more than 125,000 neurons
But that can be expected on GPU with 12Gb of memory. 

Overall, both frameworks use PyTorch, so the performance and the memory utilization should be similar. 
Interestingly, Norse created a unique LIF node that is used in the benchmarks. And to be fair, they use JIT PyTorch optimizations decorators that can potentially make the code run faster. It is able to compile the code to C++ and leverage the fast running time of the hardware, although surprisingly this change has less of effect here. Using the PyTorch JIT optimizer also makes the debugging process much harder, the Python/PyTorch compiled code throws nasty error messages that are much harder to understand, that is why we prefer not to use it in BindsNET.

Note also the standard deviation of the BindsNET script is negligible.

**Comment by Jegp** [comment]
Hi, co-author of Norse here. It's interesting you get so different results. We're not interested in rigging the benchmark, so I'll try out your code now. Would you recommend using the master branch of BindsNet or just the latest release?

**Comment by Hananel-Hazan** [comment]
Hi @Jegp great to hear from you, great job on the Norse project, we certainly have things to learn from you guys. 
You can use either one of them, currently the master branch and the latest release are the same.

**Comment by Jegp** [comment]
Likewise! BindsNet is definitely something to look up to. 

Thanks also for the reply; I'll pull the latest and run the benchmarks again.

**Comment by Jegp** [comment]
After applying your changes and evening it up a bit (Norse is recording spikes, for instance) here are the results:

![20201104benchmark](https://user-images.githubusercontent.com/1064317/98140496-ca847100-1ec5-11eb-9790-91df4031f143.png)

I'm still I'm using the newest version (0.2.8 - although I couldn't find it on pip?). The PR for Norse can be found here: https://github.com/norse/norse/pull/147 Let me know if you see anything fishy. Again, the point is to try to compare it equally. Which, admittedly, is pretty hard.

**Comment by Hananel-Hazan** [comment]
Great, now its seems right, adding monitor to the network will add the shift upward as it seems in your picture. 
You are right, it is hard to compare it equally. 
I'm surprise to see that Norse performance almost cut to half from the last test. 
 In any case, this is a good exercise for us to see if we have excessive overhead somewhere.

**Comment by Jegp** [comment]
Hard indeed. I suspect the shift in Norse performance is due to an intermediate, but superfluous, tensor I uncovered. I definitely also learned something there so this exercise seems to be mutually beneficial :-) Please don't hesitate to ping us if there are further ideas on how to benchmark this fairly.

Related, I'm quite impressed by the extremely low variance of BindsNet. Do you have an idea as to why it is so low?

**Comment by Hananel-Hazan** [comment]
I don't know why BindsNET have such a low and almost constant variance, one of the things to investigate :-)
