### ISSUE TITLE
SRM0Nodes：Is there any difference between the implementation and the paper？

### ISSUE THREAD

**Issue by lucifer2859** [BindsNET/bindsnet#452]
Layer of simplified spike response model (SRM0) neurons with stochastic threshold (escape noise). Adapted from
(Vasilaki et al., 2009) <https://intranet.physio.unibe.ch/Publikationen/Dokumente/Vasilaki2009PloSComputBio_1.pdf>.

**Comment by Hananel-Hazan** [comment]
Good question, I think there are some subtle differences, maybe @Huizerd can help with this.

**Comment by Huizerd** [comment]
Hey yeah, I can definitely answer this. First of all, the paper is a bit unclear. On page 13, equation (23) specifies the use of the SRM model. However, Figure 9 on page 15 suddenly calls these neurons 'LIF with escape noise'. So, which is it? Well, because this paper uses single exponential kernels for epsilon(t) and eta(t) in equation (23), the SRM model is actually just a LIF with a stochastic threshold, which we can compute in an iterative manner instead of having to do convolutions over all the timesteps. So let's stick with the definition of Figure 9 for now.

The differences between the neurons of Figure 9 and the `SRM0Nodes` in BindsNET are then purely architectural:
- If I remember correctly, the neurons in this paper had feedforward connections (one layer to the next) as well as lateral connections (between neurons in one layer). That would explain the two input terms in the equation for subthreshold dynamics in Figure 9: xi (or whatever Greek letter that is) for feedforward weights, and `w` for lateral weights.

Everything else should be the same: stochastic firing with escape noise has been implemented, the kernels for decay are the same. I spoke with one of the authors once and she told me they had just use a counter for the refractory period, just like the `SRM0Nodes` do.

I hope this helps; if you have any other questions, I'd be happy to help!

**Comment by lucifer2859** [comment]
Thanks very much



发自我的iPhone


------------------ Original ------------------

**Comment by Hananel-Hazan** [comment]
Thanks @Huizerd!
