### ISSUE TITLE
AssertionError: Output layer size is not equal to the size of the action space.

### ISSUE THREAD

**Issue by liuqi8827** [BindsNET/bindsnet#473]
Thanks for your great work.

I'm facing a problem when I run python `breakout_stdp.py` for RL.
I can run the gym game "BreakoutDeterministic-v4" successfully.
However, when I change "BreakoutDeterministic-v4" to "FrostbiteDeterministic-v4" or "FrostbiteNoFrameskip-v4", there is an error:
```
Traceback (most recent call last):
  File "breakout_stdp.py", line 87, in <module>
    run_pipeline(environment_pipeline, tb_writer, episode_count=1000)
  File "breakout_stdp.py", line 68, in run_pipeline
    result = pipeline.env_step()
  File "/home/hitsz/bindsnet/bindsnet/pipeline/environment_pipeline.py", line 184, in env_step
    self.action = self.action_function(self, output=self.output)
  File "/home/hitsz/bindsnet/bindsnet/pipeline/action.py", line 74, in select_softmax
    ), "Output layer size is not equal to the size of the action space."
AssertionError: Output layer size is not equal to the size of the action space.
```

Can you give some suggestions?
Thanks a lot!

**Comment by Hananel-Hazan** [comment]
This is not an issue in BindsNET and more fit to the discussions section. 

Following the error using debugger, on the exact line, the details of the problem are clearer. 
`BreakoutDeterministic-v4` has 4 outputs and the network design to have 4 outputs as well for each action. 

However, `FrostbiteDeterministic-v4`  and `FrostbiteNoFrameskip-v4` has 18 different outputs because its different game altogether. 

To use a different game, the network architecture needs to change as well.
