### ISSUE TITLE
Working with different datasets

### ISSUE THREAD

**Issue by het-25** [BindsNET/bindsnet#498]
How do I work with a new custom dataset - one that it is not available directly in bindsnet.dataset module.

**Comment by Hananel-Hazan** [comment]
You dont need to use the data loader scheme, its only for convenient. All you need is to convert your data to spikes and feed it to the input layer. You can take a look on the dataset class in BindsNET and the examples to see how we convert images to spikes.

**Comment by het-25** [comment]
Thanks for that clarification! How might I go about converting a vector of observations to corresponding spikestreams ? Does bindsnet provide a function for that?

**Comment by Hananel-Hazan** [comment]
Thank you for the great idea, currently, BindsNET does not provide a general conversion method, because each data have its own uniqueness, and general conversion usually not depends on the nature of the data. One can try to use normalization and quantification tools similar to what is found in scikit learn for that process. 

In any case, if you think that your data can serve as a general case for analog to digital conversion, I will be happy to hear about it and maybe adding your converter to BindsNET.
