### ISSUE TITLE
How to do regression with BindsNet?

### ISSUE THREAD

**Issue by mariakesa** [BindsNET/bindsnet#516]
Hello,

Thank you for a sweet package!

I have some recorded spikes and associated behavioral PC's. I would like to put the spikes through some spiking layers and predict  a behavior PC time series at the output layer. 

I don't know how to achieve this:-D Advice and pointers would be appreciated!

All the very best,
Maria

**Comment by Hananel-Hazan** [comment]
Hi @mariakesa 
Your question is not relevant to issue section, next time, please open this thread in the discussion since you asking for advice and not reporting on an issue with BindsNET.

For your question, please take a look on the example directory in BindsNET, you can find many examples to how to train network to classifying data, supervise or not supervise, some can be relevant to you some can help you point to the right direction. 

Moreover, details of the input and what you want to achieve can be helpful to understand the task.
