### ISSUE TITLE
inputs.shape for snn.run() is unclear

### ISSUE THREAD

**Issue by XiYuan68** [BindsNET/bindsnet#522]
https://github.com/BindsNET/bindsnet/blob/dcbd1c991d7dfe270398f594852de35823a642c1/bindsnet/network/network.py#L249-L257

Hi, I am using the `ann_to_snn` to convert a pretrained CNN into SNN for the MNIST task, the input_shape of CNN is [1, 28, 28]

I find the valid shape for inputs of `snn.run()` and the docstring above very confusing. It says `snn.run()` accept inputs either in shape of `[time, *input_shape]` or `[time, batch_size, *input_shape]`. 

But in my case, when I feed spike trains with the shape `[time, 1, 28, 28]`, an error is raised:
```
  File "/home/chenxiyuan/projects/PROJECT/model.py", line 105, in forward
    self.snn.run({'Input': i}, self.repeat)

  File "/home/chenxiyuan/.local/lib/python3.9/site-packages/bindsnet/network/network.py", line 360, in run
    current_inputs.update(self._get_inputs())

  File "/home/chenxiyuan/.local/lib/python3.9/site-packages/bindsnet/network/network.py", line 245, in _get_inputs
    inputs[c[1]] += self.connections[c].compute(source.s)

  File "/home/chenxiyuan/.local/lib/python3.9/site-packages/bindsnet/network/topology.py", line 372, in compute
    return F.conv2d(

RuntimeError: Expected 4-dimensional input for 4-dimensional weight [16, 1, 3, 3], but got 3-dimensional input of size [1, 28, 28] instead
```

And when I feed spike trains with the shape `[time, 5, 1, 28, 28]`, an error is also raised:

```
  File "/home/chenxiyuan/projects/PROJECT/model.py", line 103, in forward
    self.snn.run({'Input': x}, self.repeat)

  File "/home/chenxiyuan/.local/lib/python3.9/site-packages/bindsnet/network/network.py", line 360, in run
    current_inputs.update(self._get_inputs())

  File "/home/chenxiyuan/.local/lib/python3.9/site-packages/bindsnet/network/network.py", line 245, in _get_inputs
    inputs[c[1]] += self.connections[c].compute(source.s)

  File "/home/chenxiyuan/.local/lib/python3.9/site-packages/bindsnet/network/topology.py", line 463, in compute
    self.firing_rates += s.float().squeeze()

RuntimeError: output with shape [1, 16, 26, 26] doesn't match the broadcast shape [5, 16, 26, 26]
```

Only when I feed spike trains with the shape `[time, 1, 1, 28, 28]`, no error is raised. In the [conv_mnist.py example](https://github.com/BindsNET/bindsnet/blob/master/examples/mnist/conv_mnist.py), a batch_size of 1 is also adopted.

 If `[time, 1, *input_shape]` is the only valid input shape for `snn.run()`, it would be nice to update the docstring (and verify it in the function) to help new users.

**Comment by Hananel-Hazan** [comment]
Thanks for point this out, we will check it

**Comment by Hananel-Hazan** [comment]
I am sorry if the docs confuse you, please let me know how can we improve the [docs in link ](https://bindsnet-docs.readthedocs.io/guide/guide_part_i.html). 

From the docs link above, `snn.run()` accept inputs either in shape of `[time, *input_shape]` or `[time, batch_size, *input_shape]`, keeping PyTorch format. Since your input shape is `[1,28,28]`, the shape `[time, 1, 28, 28]` and shape `[time, 5, 1, 28, 28]` are incorrect. The correct shape should be `[time, 1, 1, 28, 28]` since the batch size is `1` and the input shape is `1, 28, 28` in your case. 

If however the input was 768 then input shape of `[time,768]` will work like in the example in the doc link about. 

To see how to use batch in the input, please see the [batch example ](https://github.com/BindsNET/bindsnet/blob/dcbd1c991d7dfe270398f594852de35823a642c1/examples/mnist/batch_eth_mnist.py) specifically line [189](https://github.com/BindsNET/bindsnet/blob/dcbd1c991d7dfe270398f594852de35823a642c1/examples/mnist/batch_eth_mnist.py#L189)

**Comment by XiYuan68** [comment]
In this case, it would be ideal to unify the input shape as `[time, 1, *input_shape]` for `snn.run()` and explicitly points out that `batch_size=1` in the docstring
