### ISSUE TITLE
Weight updating in "batch_eth_minst.py"

### ISSUE THREAD

**Issue by hukaidididi** [BindsNET/bindsnet#525]
In batch_eth_minst.py -->network.py (405 line):
  When updating the weight of connection "X_to_Ae", the code use PostPre update rule.
  When updating the weight of connection "Ae_to_Ai" and "Ai_to_Ae", why use NoOp update rule?
<img width="680" alt="微信图片_20211115215247" src="https://user-images.githubusercontent.com/44676210/141793445-d92e20f6-2423-48f6-8f2b-0dc3d93cb65f.png">

**Comment by SimonInParis** [comment]
As in original paper :
[https://www.frontiersin.org/articles/10.3389/fncom.2015.00099/full](url)

the only trainable connection is from the input layer to the output layer. The connection from the output to the inhibitory layer, and the connection from inhibitory back to the output layer are static, since the NoOp update rule.
