### ISSUE TITLE
where could i find an example of a sparse connection instance?

### ISSUE THREAD

**Issue by Josep777** [BindsNET/bindsnet#573]
Hello, i've been trying to find an example with numeric values for a sparse connection between two layers and haven't been able to find one. Could I get an example of this kind of connection intance with numeric values? 

Thanks in advance.

**Comment by Hananel-Hazan** [comment]
Sparse connection object exist in BindsNET, but since PyTorch doesn't fully support all the necessary operation it prevent us to use it for now. I hope in the future PyTorch will finish the necessary operations that can work with sparse weights object. 
At the meantime, you are welcome to try it yourself and let me know if things change in the last version.
