### ISSUE TITLE
Question: Can it be used for speech emotion recognition task?

### ISSUE THREAD

**Issue by RMalikM** [BindsNET/bindsnet#607]
Hi, 
Thank you for the wonderful work. I would like to train SNN for speech emotion recognition task. Can it be adapted for that? If yes, can you please give some hints what should be done for that? 

Thanks!

@djsaunde @Hananel-Hazan

**Comment by Hananel-Hazan** [comment]
Hi @RMalikM 
Thank you for using BindsNET. 

SNN can perform any task that ANN can do. The naive approach is to train ANN and convert the weights to SNN. There are many papers on the subject, and I will be happy to send you a couple of them, but a google search can give similar results. If you wish to train SNN on the data without the need for ANN, that can be done, but require converting the data you are using to a spike train (analog to digital) and using Hebbian learning like STDP to modify the weight. This is more complex approach and not every data can be trained using this method, but it is most likely doable.

Since this is not an issue with BindsNET code or a bug, I'm closing this ticket. Feel free to open one in the discussion tab.
